import { Metadata, Viewport } from 'next'
import Index from "./components"

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Chatting App',
        description: 'Generated by Next.js'
    }
}

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

export default function Page() {
    // pubnub keys
    const pubnubKeys = {
        sub: process.env.PUBNUB_SUB_KEY,
        pub: process.env.PUBNUB_PUB_KEY,
        uuid: process.env.PUBNUB_UUID
    }
    // get secret
    const accessTokenSecret = process.env.ACCESS_TOKEN_SECRET
    // get decrypt key
    const crypto = {
        key: process.env.CIPHER_KEY,
        iv: process.env.CIPHER_IV
    }
    /**
     * dark mode files:
     * index - header, footer
     * MenuButton - menu item
     * MainContent - user list container, main container
     * Profile - profile container
     * LoginPage - 
     * RegisterPage - 
     * 
     * dark mode palette: 
     * main container - indigo 800
     * user list container - violet 900
     * header, footer - indigo 400
     * profile - pink 800
     */
    // index page
    return <Index accessSecret={accessTokenSecret} pubnubKeys={pubnubKeys} crypto={crypto} />
}